// /api/charge.js
// Vercel Serverless Function — completes the real Yoco charge.
// Your SECRET key lives only here, as an environment variable — never in the frontend.
//
// Set it up in Vercel:
//   Project Settings → Environment Variables → add YOCO_SECRET_KEY = sk_live_xxxxx (or sk_test_xxxxx)
//
// Yoco charge docs: https://developer.yoco.com/online/api-reference/charges

import crypto from 'crypto';

// Used to sign download links so the PDF can only be fetched with a token
// generated by a real successful charge (see api/download.js). Falls back to
// the Yoco secret key so this works with zero extra setup, but you can set a
// dedicated DOWNLOAD_SECRET_KEY env var in Vercel if you'd prefer a separate one.
function getSigningSecret() {
  return process.env.DOWNLOAD_SECRET_KEY || process.env.YOCO_SECRET_KEY;
}

function makeDownloadToken(chargeId, expires) {
  const secret = getSigningSecret();
  return crypto.createHmac('sha256', secret).update(`${chargeId}:${expires}`).digest('hex');
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  const { token, amountInCents, currency, name, email } = req.body || {};

  if (!token || !amountInCents || !currency) {
    return res.status(400).json({ message: 'Missing token, amountInCents, or currency.' });
  }

  const YOCO_SECRET_KEY = process.env.YOCO_SECRET_KEY;
  if (!YOCO_SECRET_KEY) {
    return res.status(500).json({ message: 'Server is missing YOCO_SECRET_KEY — add it in your Vercel project settings.' });
  }

  try {
    const yocoRes = await fetch('https://online.yoco.com/v1/charges/', {
      method: 'POST',
      headers: {
        'X-Auth-Secret-Key': YOCO_SECRET_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        token,
        amountInCents,
        currency,
        metadata: { name, email, product: 'Digital Income Blueprint' }
      })
    });

    const data = await yocoRes.json();

    if (!yocoRes.ok || data.status !== 'successful') {
      return res.status(402).json({
        status: data.status || 'failed',
        message: data.displayMessage || data.message || 'Payment could not be completed.'
      });
    }

    // Payment succeeded. Issue a signed, time-limited download token instead
    // of exposing the PDF as a public static file — only someone who just
    // paid (or has this exact token) can fetch it, and it expires in 1 hour.
    const expires = Date.now() + 60 * 60 * 1000; // 1 hour from now
    const token = makeDownloadToken(data.id, expires);

    // Optional next step: send the PDF link to `email` via an email service (Resend, SendGrid, etc.)
    // and/or log the order to a database or Google Sheet. Not included here to keep this dependency-free.

    return res.status(200).json({
      status: 'successful',
      chargeId: data.id,
      downloadUrl: `/api/download?chargeId=${encodeURIComponent(data.id)}&expires=${expires}&token=${token}`
    });
  } catch (err) {
    return res.status(500).json({ message: 'Could not reach Yoco. Please try again.' });
  }
}
