// /api/download.js
// Gated download — only serves the PDF if the request carries a valid,
// unexpired token generated by api/charge.js after a real successful payment.
// The file itself lives in /private, which is never deployed as a public
// static path, so this endpoint is the only way to reach it.

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

function getSigningSecret() {
  return process.env.DOWNLOAD_SECRET_KEY || process.env.YOCO_SECRET_KEY;
}

function isValidToken(chargeId, expires, token) {
  const secret = getSigningSecret();
  if (!secret) return false;
  const expected = crypto.createHmac('sha256', secret).update(`${chargeId}:${expires}`).digest('hex');
  const a = Buffer.from(expected);
  const b = Buffer.from(token || '');
  if (a.length !== b.length) return false;
  return crypto.timingSafeEqual(a, b);
}

export default async function handler(req, res) {
  const { chargeId, expires, token } = req.query;

  if (!chargeId || !expires || !token) {
    return res.status(400).json({ message: 'Missing download credentials.' });
  }

  if (Date.now() > Number(expires)) {
    return res.status(410).json({ message: 'This download link has expired. Please contact support with your payment reference.' });
  }

  if (!isValidToken(chargeId, expires, token)) {
    return res.status(403).json({ message: 'Invalid download link.' });
  }

  try {
    const filePath = path.join(process.cwd(), 'private', 'Digital_Income_Blueprint.pdf');
    const file = fs.readFileSync(filePath);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="Digital_Income_Blueprint.pdf"');
    return res.status(200).send(file);
  } catch (err) {
    return res.status(500).json({ message: 'Could not read the guide file on the server.' });
  }
}
